# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [1]:
import numpy as np


ModuleNotFoundError: No module named 'numpy'

#### Q2 : Afficher la version de numpy et la configuration 

In [21]:
np.version.version
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


#### Q3 : Créer un vecteur nul de taille 10

In [30]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 5ème place (index 4) du vecteur

In [31]:
a[4] = 1
a


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [32]:
Z = np.arange(10, 50)
Z


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [37]:
np.flip(Z)


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [39]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Q8 : Créer une matrice identié 3x3 

In [19]:
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [20]:
np.random.rand(3, 3, 3)


array([[[0.94262341, 0.78890236, 0.96202783],
        [0.54852859, 0.32681995, 0.4720683 ],
        [0.38057362, 0.24733081, 0.73227702]],

       [[0.74945096, 0.83924627, 0.70948608],
        [0.68621493, 0.89362509, 0.75364313],
        [0.93699169, 0.74208466, 0.95007629]],

       [[0.13851192, 0.89916465, 0.22116518],
        [0.18970898, 0.50294846, 0.08027595],
        [0.27476278, 0.49553834, 0.14861682]]])

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [42]:
b = np.random.rand(10,10)
print('min',b.min())
print('max',b.max())


min 0.001698828369700145
max 0.9868182630875818


#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [58]:
Diag1 = np.diag(1+np.arange(4),k=-1)
print(Diag1)

Diag2 = np.diagflat([1,2,3,4], -1)
print(Diag2)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [46]:
listT5Rdm = np.random.rand(5)
listT5Rdm.sum()

2.878478735360643

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [47]:
np.average(listT5Rdm)


0.5756957470721286

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

In [49]:
l = [x for x in range(11)]
np.shape(l)


(11,)

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

In [59]:
np.linspace(0,1,11,endpoint=False)[1:]


array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)